config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get    '/feed',   to: 'static#feed'

  resources :user_data
  resources :clients
  resources :shoes
  resources :malfunctions
  resources :reservations
  resources :price_lists
  resources :tracks
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/malfunction.rb
class Malfunction < ApplicationRecord
    #setting up associations
    belongs_to :track

    #which attributes need to be unique
    validates :id, uniqueness: true
    validates :date, presence:true
    validates :time_from, presence:true
    #time_from should be an earlier date in the day than time_to
    validates :time_to, presence:true, comparison: { greater_than: :time_from }
end

app/controllers/malfunctions_controller.rb
class MalfunctionsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_malfunction, only: %i[ show edit update destroy ]

  swagger_controller :malfunctions, "Malfunctions"

  # GET /malfunctions or /malfunctions.json
  swagger_api :index do
    summary 'Returns all malfunctions'
    notes 'Must be logged in.'
  end
  def index
    if(logged_in?)
    @malfunctions = Malfunction.all
    end
  end

  # GET /malfunctions/1 or /malfunctions/1.json
  swagger_api :show do
    summary 'Returns a single malfunction'
    param :path, :id, :integer, :required, "Malfunction_id"
  end
  def show
  end

  # GET /malfunctions/new
  swagger_api :new do
    summary 'Returns a view for adding a malfunction'
    notes 'Must be logged in.'
  end
  def new
    if(logged_in?)
    @malfunction = Malfunction.new
    end
  end

  # GET /malfunctions/1/edit
  swagger_api :edit do
    summary 'Returns a view for editing a malfunction'
    param :path, :id, :integer, :required, "Malfunction_id"
  end
  def edit
  end

  # POST /malfunctions or /malfunctions.json
  swagger_api :create do
    summary 'Creates a malfunction'
    param :form, :id, :integer, :required, "Malfunction_id"
    param :form, :track_id, :integer, :required, "Track_id"
    param :form, :date, :date, :required, "Date"
    param :form, :time_from, :time, :required, "Time_from"
    param :form, :time_to, :time, :required, "Time_to"
    param :form, :comment, :string, "Comment"
    notes 'Must be logged in.'
  end
  def create
    if(logged_in?)
    @malfunction = Malfunction.new(malfunction_params)

    respond_to do |format|
      if @malfunction.save
        format.html { redirect_to malfunction_url(@malfunction), notice: "Malfunction was successfully created." }
        format.json { render :show, status: :created, location: @malfunction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @malfunction.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # PATCH/PUT /malfunctions/1 or /malfunctions/1.json
  swagger_api :update do
    summary 'Updates a malfunction'
    param :path, :id, :integer, :required, "Malfunction_id"
    param :form, :id, :integer, :required, "Malfunction_id"
    param :form, :track_id, :integer, :required, "Track_id"
    param :form, :date, :date, :required, "Date"
    param :form, :time_from, :time, :required, "Time_from"
    param :form, :time_to, :time, :required, "Time_to"
    param :form, :comment, :string, "Comment"
    notes 'Must be logged in.'
  end
  def update
    if(logged_in?)
    respond_to do |format|
      if @malfunction.update(malfunction_params)
        format.html { redirect_to malfunction_url(@malfunction), notice: "Malfunction was successfully updated." }
        format.json { render :show, status: :ok, location: @malfunction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @malfunction.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  # DELETE /malfunctions/1 or /malfunctions/1.json
  swagger_api :destroy do
    summary 'Deletes a malfunction'
    param :path, :id, :integer, :required, "Malfunction_id"
    notes 'Must be logged in.'
  end
  def destroy
    if(logged_in?)
    @malfunction.destroy

    respond_to do |format|
      format.html { redirect_to malfunctions_url, notice: "Malfunction was successfully destroyed." }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_malfunction
      @malfunction = Malfunction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def malfunction_params
      params.require(:malfunction).permit(:malfunction_id, :track_id, :date, :time_from, :time_to, :comment)
      #params.require(:malfunction).permit(:date, :time_from, :time_to, :comment)
    end
end

app/helpers/malfunctions_helper.rb
module MalfunctionsHelper
end

app/views/malfunctions/_form.html.erb
<%= form_with(model: malfunction) do |form| %>
  <% if malfunction.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(malfunction.errors.count, "error") %> prohibited this malfunction from being saved:</h2>

      <ul>
        <% malfunction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :track_id, style: "display: block" %>
    <%= form.number_field :track_id %>
  </div>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :time_from, style: "display: block" %>
    <%= form.time_field :time_from %>
  </div>

  <div>
    <%= form.label :time_to, style: "display: block" %>
    <%= form.time_field :time_to %>
  </div>

  <div>
    <%= form.label :comment, style: "display: block" %>
    <%= form.text_field :comment %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/malfunctions/_malfunction.html.erb
<div id="<%= dom_id malfunction %>">

  <p>
    <strong>Malfunction_id:</strong>
    <%= malfunction.id %>
  </p>

  <p>
    <strong>Track:</strong>
    <%= malfunction.track_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= malfunction.date %>
  </p>

  <p>
    <strong>Time from:</strong>
    <%= malfunction.time_from %>
  </p>

  <p>
    <strong>Time to:</strong>
    <%= malfunction.time_to %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= malfunction.comment %>
  </p>

</div>

app/views/malfunctions/edit.html.erb
<h1>Editing malfunction</h1>

<%= render "form", malfunction: @malfunction %>

<br>

<div>
  <%= link_to "Show this malfunction", @malfunction %> |
  <%= link_to "Back to malfunctions", malfunctions_path %>
</div>

app/views/malfunctions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Malfunctions</h1>

<div id="malfunctions">
  <% @malfunctions.each do |malfunction| %>
    <%= render malfunction %>
    <p>
      <%= link_to "Show this malfunction", malfunction %>
    </p>
  <% end %>
</div>

<%= link_to "New malfunction", new_malfunction_path %>

app/views/malfunctions/new.html.erb
<h1>New malfunction</h1>

<%= render "form", malfunction: @malfunction %>

<br>

<div>
  <%= link_to "Back to malfunctions", malfunctions_path %>
</div>

app/views/malfunctions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @malfunction %>

<div>
  <%= link_to "Edit this malfunction", edit_malfunction_path(@malfunction) %> |
  <%= link_to "Back to malfunctions", malfunctions_path %>

  <%= button_to "Destroy this malfunction", @malfunction, method: :delete %>
</div>