config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get    '/feed',   to: 'static#feed'

  resources :user_data
  resources :clients
  resources :shoes
  resources :malfunctions
  resources :reservations
  resources :price_lists
  resources :tracks
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/price_list.rb
class PriceList < ApplicationRecord
    #defining an enum
    enum item_type: {
        track: 1,
        shoe: 2
    }

    #defining an enum
    enum weekday: {
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6,
        sunday: 7
    }

    #setting up associations
    has_many :reservations

    #which attributes need to be filled out during creation, which ones need to be unique
    validates :id, uniqueness: true
    validates :item_type, presence:true
    validates :price, presence:true
    validates :time_from, presence:true
    #time_from should be an earlier date in the day than time_to
    validates :time_to, presence:true, comparison: { greater_than: :time_from }
    validates :weekday, presence:true
end

app/controllers/price_lists_controller.rb
class PriceListsController < ApplicationController
  skip_before_action :verify_authenticity_token

  before_action :set_price_list, only: %i[ show edit update destroy ]

  swagger_controller :price_lists, "PriceLists"

  # GET /price_lists or /price_lists.json
  swagger_api :index do
    summary 'Returns all price lists'
  end
  def index
    @price_lists = PriceList.all
  end

  # GET /price_lists/1 or /price_lists/1.json
  swagger_api :show do
    summary 'Returns a single price list'
    param :path, :id, :integer, :required, "Price_list_id"
  end
  def show
  end

  # GET /price_lists/new
  swagger_api :new do
    summary 'Returns a view for adding a price list'
  end
  def new
    @price_list = PriceList.new
  end

  # GET /price_lists/1/edit
  swagger_api :edit do
    summary 'Returns a view for editing a price list'
    param :path, :id, :integer, :required, "Price_list_id"
  end
  def edit
  end

  # POST /price_lists or /price_lists.json
  swagger_api :create do
    summary 'Creates a price list'
    param :form, :id, :integer, :required, "Price_list_id"
    param :form, :price, :integer, :required, "Price"
    param :form, :item_type, :integer, :required, "Item_type"
    param :form, :weekday, :integer, :required, "Weekday"
    param :form, :time_from, :time, :required, "Time_from"
    param :form, :time_to, :time, :required, "Time_to"
    param :form, :current, :boolean, :required, "Current"
    notes 'Must be logged in.'
  end
  def create
    if(logged_in?)
    @price_list = PriceList.new(price_list_params)

    respond_to do |format|
      if @price_list.save
        format.html { redirect_to price_list_url(@price_list), notice: "Price list was successfully created." }
        format.json { render :show, status: :created, location: @price_list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @price_list.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # PATCH/PUT /price_lists/1 or /price_lists/1.json
  swagger_api :update do
    summary 'Updates a price list'
    param :path, :id, :integer, :required, "Price_list_id"
    param :form, :id, :integer, :required, "Price_list_id"
    param :form, :price, :integer, :required, "Price"
    param :form, :item_type, :integer, :required, "Item_type"
    param :form, :weekday, :integer, :required, "Weekday"
    param :form, :time_from, :time, :required, "Time_from"
    param :form, :time_to, :time, :required, "Time_to"
    param :form, :current, :boolean, :required, "Current"
    notes 'Must be logged in.'
  end
  def update
    if(logged_in?)
    respond_to do |format|
      if @price_list.update(price_list_params)
        format.html { redirect_to price_list_url(@price_list), notice: "Price list was successfully updated." }
        format.json { render :show, status: :ok, location: @price_list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @price_list.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /price_lists/1 or /price_lists/1.json
  swagger_api :destroy do
    summary 'Destroys a price list'
    param :path, :id, :integer, :required, "Price_list_id"
    notes 'Must be logged in.'
  end
  def destroy
    if(logged_in?)
    @price_list.destroy

    respond_to do |format|
      format.html { redirect_to price_lists_url, notice: "Price list was successfully destroyed." }
      format.json { head :no_content }
    end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_list
      @price_list = PriceList.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def price_list_params
      params.require(:price_list).permit(:id, :price, :item_type, :weekday, :time_from, :time_to, :current)
      #params.require(:price_list).permit(:price_list_id, :price, :item_type, :weekday, :time_from, :time_to, :current)
    end
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/views/price_lists/_form.html.erb
<%= form_with(model: price_list) do |form| %>
  <% if price_list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(price_list.errors.count, "error") %> prohibited this price_list from being saved:</h2>

      <ul>
        <% price_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :item_type, style: "display: block" %>
    <%= form.text_field :item_type %>
  </div>

  <div>
    <%= form.label :weekday, style: "display: block" %>
    <%= form.text_field :weekday %>
  </div>

  <div>
    <%= form.label :time_from, style: "display: block" %>
    <%= form.time_field :time_from %>
  </div>

  <div>
    <%= form.label :time_to, style: "display: block" %>
    <%= form.time_field :time_to %>
  </div>

  <div>
    <%= form.label :current, style: "display: block" %>
    <%= form.check_box :current %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/price_lists/_price_list.html.erb
<div id="<%= dom_id price_list %>">

  <p>
    <strong>Price_list_id:</strong>
    <%= price_list.id %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= price_list.price %>
  </p>

  <p>
    <strong>Item type:</strong>
    <%= price_list.item_type %>
  </p>

  <p>
    <strong>Weekday:</strong>
    <%= price_list.weekday %>
  </p>

  <p>
    <strong>Time from:</strong>
    <%= price_list.time_from %>
  </p>

  <p>
    <strong>Time to:</strong>
    <%= price_list.time_to %>
  </p>

  <p>
    <strong>Current:</strong>
    <%= price_list.current %>
  </p>

</div>

app/views/price_lists/edit.html.erb
<h1>Editing price list</h1>

<%= render "form", price_list: @price_list %>

<br>

<div>
  <%= link_to "Show this price list", @price_list %> |
  <%= link_to "Back to price lists", price_lists_path %>
</div>

app/views/price_lists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Price lists</h1>

<div id="price_lists">
  <% @price_lists.each do |price_list| %>
    <%= render price_list %>
    <p>
      <%= link_to "Show this price list", price_list %>
    </p>
  <% end %>
</div>

<%= link_to "New price list", new_price_list_path %>

app/views/price_lists/new.html.erb
<h1>New price list</h1>

<%= render "form", price_list: @price_list %>

<br>

<div>
  <%= link_to "Back to price lists", price_lists_path %>
</div>

app/views/price_lists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @price_list %>

<div>
  <%= link_to "Edit this price list", edit_price_list_path(@price_list) %> |
  <%= link_to "Back to price lists", price_lists_path %>

  <%= button_to "Destroy this price list", @price_list, method: :delete %>
</div>