config/routes.rb
Rails.application.routes.draw do
  root to: 'static#index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  delete '/logout',  to: 'sessions#destroy'
  get '/api' => redirect('/swagger/dist/index.html?url=/api-docs.json')
  get    '/feed',   to: 'static#feed'

  resources :user_data
  resources :clients
  resources :shoes
  resources :malfunctions
  resources :reservations
  resources :price_lists
  resources :tracks
  resources :employees
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
    #setting up associations
    belongs_to :user_datum
    has_many :reservations
    
    #which attributes need to be unique
    validates :id, uniqueness: true
end

app/models/employee.rb
class Employee < ApplicationRecord
    #setting up associations
    belongs_to :user_datum
    
    #which attributes need to be unique
    validates :id, uniqueness: true
end

app/models/malfunction.rb
class Malfunction < ApplicationRecord
    #setting up associations
    belongs_to :track

    #which attributes need to be unique
    validates :id, uniqueness: true
    validates :date, presence:true
    validates :time_from, presence:true
    #time_from should be an earlier date in the day than time_to
    validates :time_to, presence:true, comparison: { greater_than: :time_from }
end

app/models/price_list.rb
class PriceList < ApplicationRecord
    #defining an enum
    enum item_type: {
        track: 1,
        shoe: 2
    }

    #defining an enum
    enum weekday: {
        monday: 1,
        tuesday: 2,
        wednesday: 3,
        thursday: 4,
        friday: 5,
        saturday: 6,
        sunday: 7
    }

    #setting up associations
    has_many :reservations

    #which attributes need to be filled out during creation, which ones need to be unique
    validates :id, uniqueness: true
    validates :item_type, presence:true
    validates :price, presence:true
    validates :time_from, presence:true
    #time_from should be an earlier date in the day than time_to
    validates :time_to, presence:true, comparison: { greater_than: :time_from }
    validates :weekday, presence:true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    #setting up associations
    belongs_to :shoe
    belongs_to :track
    belongs_to :price_list
    belongs_to :client

    #which attributes need to be filled out during creation, which ones need to be unique
    validates :id, uniqueness: true
    validates :date, presence:true
    validates :time_from, presence:true
    #time_from should be an earlier date in the day than time_to
    validates :time_to, presence:true, comparison: { greater_than: :time_from }
end

app/models/shoe.rb
class Shoe < ApplicationRecord
    #setting up associations
    has_many :reservations

    #which attributes need to filled out during creation, which ones need to be unique
    validates :id, uniqueness: true
    validates :size, presence:true
end

app/models/track.rb
class Track < ApplicationRecord
    #setting up associations
    has_many :malfunctions
    has_many :reservations

    #which attributes should be unique
    validates :id, uniqueness: true
end

app/models/user_datum.rb
class UserDatum < ApplicationRecord
  #setting up associations
  has_one :client
  has_one :employee

  #for login
  has_secure_password
  has_secure_password

  #which attributes should be filled out, which ones should be unique
  validates :id, uniqueness: true
  #make sure an actual email is passed and not just some random junk
  validates :email, presence:true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, presence:true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence:true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :login, presence:true, uniqueness: true
  #password needs to be at least 6 characters long
  validates :password, presence:true, length: {minimum: 6}

  #for authorization
  def invalidate_token
    self.update_columns(token: nil)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/malfunctions_helper.rb
module MalfunctionsHelper
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user_datum)
        session[:user_datum_id] = user_datum.id
    end
        
    def current_user_datum
        @current_user_datum ||= UserDatum.find_by(id: session[:user_datum_id])
    end

    def logged_in?
        !current_user_datum.nil?
    end

    def log_out
        session.delete(:user_datum_id)
        @current_user_datum = nil
    end

    def require_token
        respond_to do |format|
            format.json {
                authenticate_token || render_unauthorized("Access denied")
            }
            format.html { }
        end
    end

    def render_unauthorized(message)
        errors = { errors: [ { detail: message } ] }
        render json: errors, status: :unauthorized
    end

    def authenticate_token
        authenticate_with_http_token do |token, options|
        @current_user_datum ||= UserDatum.find_by(token: token)
    end
  end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/user_data_helper.rb
module UserDataHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "/assets/application.js", "data-turbo-track": "reload", defer: true %>
    <title>PsiimProjekt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <ul>
  <li><%= link_to "Main page", root_path %></li>
  <li><%= link_to "Price lists", price_lists_path %></li>
  <li><%= link_to "Tracks", tracks_path %></li>
  <li><%= link_to "Shoes", shoes_path %></li>
  <li><%= link_to "Reservations", reservations_path %></li>
  <!--stuff below should only be visible to employees-->
  <li><%= link_to "User data", user_data_path %></li>
  <% if logged_in? %> <!--TU-->
    <li><%= link_to "Clients", clients_path %></li>
    <li><%= link_to "Employees", employees_path %></li>
    <li><%= link_to "Malfunctions", malfunctions_path %></li>
    <li><%= link_to current_user_datum.first_name, current_user_datum %></li>
    <li><%= link_to "Log Out", logout_path, method: :delete %></li>
  <% else %>
    <li><%= link_to "Log In", login_path %></li>
  <% end %>
</ul>
  </head>

  <body>
   <% if logged_in? %>
    Logged in as <%= current_user_datum.first_name %>
    <%= link_to "Profile", current_user_datum %>
    <%= link_to "Log Out", logout_path, method: :get %>
  <% else %>
    <%= link_to "Log In", login_path %>
  <% end %>
  <%= yield %>
  </body>
</html>